//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionVentas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventario
    {
        public int ProductoProveedorId { get; set; }
        public int Producto_Id { get; set; }
        public int Proveedor_Id { get; set; }
    
        public virtual Productos Productos { get; set; }
        public virtual Proveedores Proveedores { get; set; }
    }
}
